version: "3"

services:
  webserver:
    build: 
      context: .
    container_name: 'houzcontrol'
    restart: 'always'
    environment:
      PORT: '/dev/ttyUSB0' 
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    ports:
      - '3000:3000'
